export const storeProducts = [
  {
    id: 1,
    title: "Aceite de Tea Tree con Manuca y Rosalina",
    img: "img/product-1.png",
    price: 15000,
    company: "Just",
    info:
      "En sus viajes de exploración por Australia, el Capitán Cook aprendió de los indígenas, las maravillosas propiedades del tea tree al brindarles primeros auxilios a sus soldados como desinfectante, desinflamatorio, analgésico y cicatrizante. Desde entonces, el tea tree se ha utilizado extensamente para temas relacionados con la piel por ser muy efectivo y delicado a la vez.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Aceite Esencial de Palmarosa",
    img: "img/product-2.png",
    price: 7000,
    company: "Just",
    info:
      "El Aceite Esencial de Palmarosa es símbolo de equilibrio y tranquilidad. Su aroma a rocío recién formado y a rosa lo vuelve sutil y elegante a la vez. Brinda una sensación de armonía y paz total. Ayuda a aclarar las ideas y aleja los malos pensamientos para permitirnos tomar las mejores decisiones sin quedar estancados en el mismo lugar. Los momentos fluyen sin dificultad.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Crema de Enebro",
    img: "img/product-3.png",
    price: 7000,
    company: "Just",
    info:
      "El calor y los masajes son la recomendación más antigua para aflojar las tensiones musculares y las molestias que éstas producen a raíz de problemas de contracturas, postura o de la actividad misma. Un masaje con Crema de Enebro relaja los músculos, facilita el movimiento de personas mayores y también, por su acción calorífica, ayuda a preparar el cuerpo antes de los deportes y la actividad física.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Aceite Esencial de Romero",
    img: "img/product-4.png",
    price: 7000,
    company: "Just",
    info:
      "El Aceite Esencial de Romero posee un aroma especiado, limpio y refrescante que renueva las fuerzas perdidas ante el cansancio físico y mental. Despierta, activa y moviliza para que tus energías y tu tiempo rindan al máximo y el disfrute sea mayor.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Aceite Esencial de Lavanda",
    img: "img/product-5.png",
    price: 7000,
    company: "Just",
    info:
      "Con un aroma floral, fresco y con un dejo herbal, el Aceite Esencial de Lavanda es tan versátil como útil en cualquier hogar. Su aroma calma y aquieta los nervios, la ansiedad y el estrés ayudando a conciliar el sueño cuando resulta difícil bajar revoluciones. Es el aceite ideal para tener en el botiquín de primeros auxilios a la hora de reconfortar la piel en casos de quemaduras, eczemas y alergias.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Óleo 31",
    img: "img/product-6.png",
    price: 7000,
    company: "Just",
    info:
      "¿Molestias? ¿Dolores de cabeza? Mediante el masaje relaja, devolviendo la energía y la agilidad naturales del cuerpo. Afloja las tensiones que generan dolores musculares y de cabeza. El Óleo 31 potencia los beneficios de otros productos Just creando una sinergia única.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Bálsamo Corporal",
    img: "img/product-7.png",
    price: 7000,
    company: "Just",
    info:
      "Una fricción vigorizante estimula la circulación evitando la formación de moretones y hematomas. Esta combinación de extracto de árnica junto a exquisitos ingredientes activos naturales, protege de agresiones externas reconfortando las molestias causadas por golpes y picaduras de insectos. Ideal para niños, propensos a golpearse y formar moretones.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Aceite Esencial de Limón",
    img: "img/product-8.png",
    price: 7000,
    company: "Just",
    info:
      "El aroma penetrante del Aceite Esencial de Limón se hace presente para liberar la energía bloqueada y estimular la creatividad y la concentración. Aparece como una bocanada de aire fresco, cítrico e inspirador dejando tras su paso alegría positiva, sonrisas, buen humor y ganas de hacer.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Anti-Stress",
    img: "img/product-9.png",
    price: 7000,
    company: "Just",
    info:
      "Una sinergia particular y equilibrada de 15 aceites esenciales naturales combinados para brindar una sensación única de bienestar y relajación que permite afrontar los momentos de alto estrés de manera armónica. Una suave fricción detrás de las orejas, en la nuca o las muñecas te permiten disfrutar de sus beneficios. También usándolo en un baño de inmersión, en el sauna o en el hornillo de aromaterapia podrás apreciar plenamente sus vapores tranquilizantes.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Esencia para baño de Enebro",
    img: "img/product-101.png",
    price: 7000,
    company: "Just",
    info:
      "Un baño de inmersión caliente con Esencia para Baño de Enebro brinda una acción reconfortante instantánea.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = [
  {
    id: 1,
    code: "4110",
    presentation: "20 ml",
    img: "img/product-1.png",
    price: 15.000,
    company: "Just",
    info:
      "En sus viajes de exploración por Australia, el Capitán Cook aprendió de los indígenas, las maravillosas propiedades del tea tree al brindarles primeros auxilios a sus soldados como desinfectante, desinflamatorio, analgésico y cicatrizante. Desde entonces, el tea tree se ha utilizado extensamente para temas relacionados con la piel por ser muy efectivo y delicado a la vez.",
    inCart: false,
    count: 0,
    total: 0,
  },
  // {
  //   id: 2,
  //   code: "1016",
  //   presentation: "10 ml",
  //   img: "img/product-2.png",
  //   price: 7.000,
  //   company: "Just",
  //   info:
  //     "El Aceite Esencial de Palmarosa es símbolo de equilibrio y tranquilidad. Su aroma a rocío recién formado y a rosa lo vuelve sutil y elegante a la vez. Brinda una sensación de armonía y paz total. Ayuda a aclarar las ideas y aleja los malos pensamientos para permitirnos tomar las mejores decisiones sin quedar estancados en el mismo lugar. Los momentos fluyen sin dificultad.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  // {
  //   id: 3,
  //   code: "3500",
  //   presentation: "96 g.",
  //   img: "img/product-3.png",
  //   price: 7.000,
  //   company: "Just",
  //   info:
  //     "El calor y los masajes son la recomendación más antigua para aflojar las tensiones musculares y las molestias que éstas producen a raíz de problemas de contracturas, postura o de la actividad misma. Un masaje con Crema de Enebro relaja los músculos, facilita el movimiento de personas mayores y también, por su acción calorífica, ayuda a preparar el cuerpo antes de los deportes y la actividad física.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  // {
  //   id: 4,
  //   code: "1017",
  //   presentation: "10 ml",
  //   img: "img/product-4.png",
  //   price: 7.000,
  //   company: "Just",
  //   info:
  //     "El Aceite Esencial de Romero posee un aroma especiado, limpio y refrescante que renueva las fuerzas perdidas ante el cansancio físico y mental. Despierta, activa y moviliza para que tus energías y tu tiempo rindan al máximo y el disfrute sea mayor.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  // {
  //   id: 5,
  //   code: "1010",
  //   presentation: "10 ml",
  //   img: "img/product-5.png",
  //   price: 7.000,
  //   company: "Just",
  //   info:
  //     "Con un aroma floral, fresco y con un dejo herbal, el Aceite Esencial de Lavanda es tan versátil como útil en cualquier hogar. Su aroma calma y aquieta los nervios, la ansiedad y el estrés ayudando a conciliar el sueño cuando resulta difícil bajar revoluciones. Es el aceite ideal para tener en el botiquín de primeros auxilios a la hora de reconfortar la piel en casos de quemaduras, eczemas y alergias.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  // {
  //   id: 6,
  //   code: "3000",
  //   presentation: "20 ml",
  //   img: "img/product-7.png",
  //   price: 7000,
  //   company: "Just",
  //   info:
  //     "¿Molestias? ¿Dolores de cabeza? Mediante el masaje relaja, devolviendo la energía y la agilidad naturales del cuerpo. Afloja las tensiones que generan dolores musculares y de cabeza. El Óleo 31 potencia los beneficios de otros productos Just creando una sinergia única.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  // {
  //   id: 7,
  //   code: "3100",
  //   presentation: "290 ml",
  //   img: "img/product-7.png",
  //   price: 7000,
  //   company: "Just",
  //   info:
  //     "Una fricción vigorizante estimula la circulación evitando la formación de moretones y hematomas. Esta combinación de extracto de árnica junto a exquisitos ingredientes activos naturales, protege de agresiones externas reconfortando las molestias causadas por golpes y picaduras de insectos. Ideal para niños, propensos a golpearse y formar moretones.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  // {
  //   id: 8,
  //   code: "1011",
  //   presentation: "10 ml",
  //   img: "img/product-8.png",
  //   price: 7000,
  //   company: "Just",
  //   info:
  //     "El aroma penetrante del Aceite Esencial de Limón se hace presente para liberar la energía bloqueada y estimular la creatividad y la concentración. Aparece como una bocanada de aire fresco, cítrico e inspirador dejando tras su paso alegría positiva, sonrisas, buen humor y ganas de hacer.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  //   id: 9,
  //   code: "2200",
  //   presentation: "20 ml",
  //   img: "img/product-8.png",
  //   price: 7000,
  //   company: "Just",
  //   info:
  //     "Una sinergia particular y equilibrada de 15 aceites esenciales naturales combinados para brindar una sensación única de bienestar y relajación que permite afrontar los momentos de alto estrés de manera armónica. Una suave fricción detrás de las orejas, en la nuca o las muñecas te permiten disfrutar de sus beneficios. También usándolo en un baño de inmersión, en el sauna o en el hornillo de aromaterapia podrás apreciar plenamente sus vapores tranquilizantes.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
  //   id: 10,
  //   code: "3502",
  //   presentation: "50 ml",
  //   img: "img/product-8.png",
  //   price: 7000,
  //   company: "Just",
  //   info:
  //     "Un baño de inmersión caliente con Esencia para Baño de Enebro brinda una acción reconfortante instantánea.",
  //   inCart: false,
  //   count: 0,
  //   total: 0,
  // },
];
